openapi: 3.0.1
info:
  title: LittleCI
  version: 0.1.0
  license:
    name: Parity Public License
    url: 'https://paritylicense.com/versions/6.0.0.html'
  contact:
    email: hi@littleci.org
  termsOfService: 'https://littleci.org/terms/'
  description: API documentation
paths:
  '/login':
    post:
      tags:
        - config
      summary: Login a user
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  '/jobs':
    get:
      tags:
        - jobs
      summary: Get a list of all jobs
      operationId: getAllJobs
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobSummary'
      security:
        - user_auth: []
  '/repositories/{repositoryName}/jobs/{jobId}/output':
    get:
      tags:
        - logs
      summary: Get a jobs output log
      operationId: getOutputByJobId
      parameters:
        - name: repositoryName
          in: path
          description: Name of repository
          required: true
          schema:
            type: string
        - name: jobId
          in: path
          description: Job ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
      security:
        - user_auth: []
  '/repositories/{repositoryName}/jobs/{jobId}':
    get:
      tags:
        - jobs
      summary: Get a job
      operationId: getJobById
      parameters:
        - name: repositoryName
          in: path
          description: Name of repository
          required: true
          schema:
            type: string
        - name: jobId
          in: path
          description: Job ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
      security:
        - user_auth: []
  '/repositories/{repositoryName}/jobs':
    get:
      tags:
        - jobs
      summary: Get a list of jobs for a repository
      operationId: getJobsByRepository
      parameters:
        - name: repositoryName
          in: path
          description: Name of repository
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
      security:
        - user_auth: []
  '/repositories/{repositoryName}':
    get:
      tags:
        - repositories
      summary: Get a repository
      operationId: getRepository
      parameters:
        - name: repositoryName
          in: path
          description: Name of repository
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
      security:
        - user_auth: []
  '/repositories/{repositoryId}':
    delete:
      tags:
        - repositories
      summary: Delete a repository
      operationId: deleteRepository
      parameters:
        - name: repositoryId
          in: path
          description: ID of repository
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      security:
        - user_auth: []
  /repositories:
    post:
      tags:
        - repositories
      summary: Add a new repository
      operationId: addRepository
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Repository'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
      security:
        - user_auth: []
    put:
      tags:
        - repositories
      summary: Update a repository
      operationId: updateRepository
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Repository'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
      security:
        - user_auth: []
    get:
      tags:
        - repositories
      summary: Get a list of configured repositories
      operationId: getRepositories
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
      security:
        - user_auth: []
  /users:
    get:
      tags:
        - users
      summary: Get a list of users
      operationId: getUsers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      security:
        - user_auth: []
    post:
      tags:
        - users
      summary: Add a new user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - user_auth: []
    put:
      tags:
        - users
      summary: Update a user
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - user_auth: []
  /users/password:
    put:
      tags:
        - users
      summary: Set current users password
      operationId: setPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPassword'
      responses:
        '200':
          description: successful operation
      security:
        - user_auth: []
  '/users/{userId}':
    get:
      tags:
        - users
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - user_auth: []
    delete:
      tags:
        - users
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
      security:
        - user_auth: []
  /config:
    get:
      tags:
        - config
      summary: Get client configuration properties
      operationId: getConfig
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
      security:
        - user_auth: []
  '/notify/{repositoryName}':
    parameters:
      - name: repositoryName
        in: path
        required: true
        schema:
            type: string
    get:
      operationId: notifyRepository
      description: Trigger job with secret key header
      tags:
        - notify
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              examples: {}
      security:
        - secret_key_header: []
        - secret_query_param: []
    post:
      operationId: notifyRepositoryWithData
      description: Trigger job with secret key header and extra data
      tags:
        - notify
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              Example payload:
                value:
                  SOME_ENVIRONMENT_VARIABLE: FOOBARBAZ
        description: Optional key/value pairs to be injected into a job as environment variables
      security:
        - secret_key_header: []
        - secret_query_param: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
  '/notify/{repositoryName}/{service}':
    parameters:
      - name: repositoryName
        in: path
        required: true
        schema:
            type: string
      - name: service
        in: path
        required: true
        schema:
          type: string
          enum:
          - github
    post:
      operationId: notifyRepositoryWithService
      description: Trigger job with a service-specific payload
      tags:
        - notify
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/GithubPayload'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
      security:
        - github_signature: []
components:
  schemas:
    ExecutionLog:
      type: object
      properties:
        status:
          type: string
          description: Execution status of this job
          enum:
            - cancelled
            - queued
            - running
            - failed
            - completed
        exit_code:
          type: integer
          format: int64
          nullable: true
        created_at:
          type: string
          description: Timestamp of execution status change
          format: date-time
    ExecutionStatus:
      type: string
      description: Execution status of this job
      enum:
        - cancelled
        - queued
        - running
        - failed
        - completed
    User:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
        password:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    UserPassword:
      type: object
      properties:
        password:
          type: string
    Job:
      type: object
      properties:
        id:
          type: string
          description: Job ID
        repository_id:
          type: string
          description: ID of the repository associated with this job
        status:
          $ref: '#/components/schemas/ExecutionStatus'
        exit_code:
          type: integer
          format: int64
          nullable: true
        data:
          type: object
          description: Data passed into the job
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        logs:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionLog'
    JobSummary:
      type: object
      properties:
        id:
          type: string
          description: Job ID
        status:
          $ref: '#/components/schemas/ExecutionStatus'
        repository_slug:
          type: string
          description: Slug of the repository associated with this job
        repository_name:
          type: string
          description: Repository name
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Repository:
      type: object
      properties:
        id:
          type: string
          description: Identifier
        slug:
          type: string
          description: URL friendly slug
        name:
          type: string
          description: Repository name
        run:
          type: string
          description: Command to execute
        working_dir:
          type: string
          description: Working dir to execute the command in
        variables:
          type: object
        triggers:
          type: object
        webhooks:
          type: object
        secret:
          type: string
          description: Secret to trigger jobs
    Config:
      type: object
      properties:
        signature:
          type: string
          description: Hashed signature for use when triggering jobs
        data_dir:
          type: string
          description: Storage location of LittleCI data on the host machine
        network_host:
          type: string
          description: Network host which LittleCI binds to when started
        port:
          type: string
          description: Port LittleCI binds to
        log_to_syslog:
          type: boolean
          description: Whether LittleCI should log to syslog
    GithubPayload:
      type: object
      properties:
        ref:
          type: string
        before:
          type: string
        after:
          type: string
        head_commit:
          type: string
    UserCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    UserResponse:
      type: object
      properties:
        username:
          type: string
        exp:
          type: string
        token:
          type: string
  securitySchemes:
    user_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    secret_key_header:
      name: X-Secret-Key
      type: apiKey
      in: header
      description: ''
    github_signature:
      name: X-Hub-Signature
      type: apiKey
      in: header
    secret_query_param:
      name: key
      type: apiKey
      in: query
tags:
  - name: config
    description: Client configuration
  - name: repositories
    description: Configured repositories
  - name: jobs
    description: ''
  - name: logs
    description: Log endpoints
  - name: notify
    description: Trigger a job for a repository
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
